extends SceneTree

## Offline-only generator. Converts the authored Scene9 cloud PNG into a
## compressed GDScript blueprint so the runtime scene never samples the PNG.

const SOURCE_PATH := "res://assets/scenes/scene9/scene9_cloud_layer.png"
const OUTPUT_PATH := "res://src/ui/components/scene9_cloud_blueprint.gd"
const BASE64_LINE_LENGTH := 100


func _initialize() -> void:
	call_deferred(&"_run")


func _run() -> void:
	var image := Image.load_from_file(SOURCE_PATH)
	if image == null or image.is_empty():
		push_error("Unable to load Scene9 cloud source: %s" % SOURCE_PATH)
		quit(1)
		return
	if image.get_format() != Image.FORMAT_RGBA8:
		image.convert(Image.FORMAT_RGBA8)
	var raw_rgba := image.get_data()
	var compressed := raw_rgba.compress(FileAccess.COMPRESSION_DEFLATE)
	var encoded := Marshalls.raw_to_base64(compressed)
	var used_rect := image.get_used_rect()
	var source := _build_blueprint_source(
			image.get_size(), used_rect, raw_rgba, encoded)
	var output := FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if output == null:
		push_error("Unable to write Scene9 cloud blueprint: %s" % OUTPUT_PATH)
		quit(1)
		return
	output.store_string(source)
	output.close()
	print("SCENE9_CLOUD_BLUEPRINT_GENERATED size=", image.get_size(),
			" used_rect=", used_rect, " raw_bytes=", raw_rgba.size(),
			" compressed_bytes=", compressed.size(),
			" rgba_sha256=", _sha256_text(raw_rgba))
	quit(0)


func _build_blueprint_source(
		source_size: Vector2i,
		used_rect: Rect2i,
		raw_rgba: PackedByteArray,
		encoded: String) -> String:
	var encoded_lines: Array[String] = []
	for offset: int in range(0, encoded.length(), BASE64_LINE_LENGTH):
		encoded_lines.append("\t\"%s\"" % encoded.substr(
				offset, mini(BASE64_LINE_LENGTH, encoded.length() - offset)))
	var encoded_expression := " +\n".join(encoded_lines)
	var rgba_sha256 := _sha256_text(raw_rgba)
	return """# Generated by res://tools/generate_scene9_cloud_blueprint.gd.
# Do not hand-edit. The runtime reconstructs the authored pixels from this
# code-owned, lossless RGBA payload and never loads scene9_cloud_layer.png.
extends RefCounted

const SOURCE_SIZE := Vector2i(%d, %d)
const SOURCE_USED_RECT := Rect2i(%d, %d, %d, %d)
const SOURCE_RGBA_BYTE_COUNT := %d
const SOURCE_RGBA_SHA256 := \"%s\"
const SOURCE_RGBA_DEFLATE_BASE64 := (\n%s\n)


static func source_rgba() -> PackedByteArray:
	var compressed := Marshalls.base64_to_raw(SOURCE_RGBA_DEFLATE_BASE64)
	var raw := compressed.decompress(
			SOURCE_RGBA_BYTE_COUNT, FileAccess.COMPRESSION_DEFLATE)
	assert(raw.size() == SOURCE_RGBA_BYTE_COUNT)
	var hashing := HashingContext.new()
	hashing.start(HashingContext.HASH_SHA256)
	hashing.update(raw)
	assert(hashing.finish().hex_encode() == SOURCE_RGBA_SHA256)
	return raw
""" % [
		source_size.x, source_size.y,
		used_rect.position.x, used_rect.position.y,
		used_rect.size.x, used_rect.size.y,
		raw_rgba.size(), rgba_sha256, encoded_expression,
	]


func _sha256_text(data: PackedByteArray) -> String:
	var hashing := HashingContext.new()
	hashing.start(HashingContext.HASH_SHA256)
	hashing.update(data)
	return hashing.finish().hex_encode()
